### ISSUE TITLE
sutra number error

### ISSUE THREAD

**Issue by vvasuki** [ashtadhyayi-com/data#105]
Push failed due to denial of permission. The following correction needed.

![image](https://user-images.githubusercontent.com/2664797/173720572-47e81e1f-7a06-4e05-8234-cb1a2cac4d73.png)

**Comment by neeleshb** [comment]
Ah. I am in the process of moving all the data from ashtadhyayi-com/data to /ashtadhyayi-com/data-edit,  which provides a very user friendly interface of editing the commentaries. That's why the repository was made read-only. Unfortunately that work is taking more time due to other commitments. Nevertheless, I will fix this issue on my end, and will try to speed up that process. Thanks.
